package communityhub.gui;

import communityhub.Announcement;
import communityhub.AnnouncementTable;
import communityhub.DB.Database;
import communityhub.Group;
import communityhub.users.BasicUser;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.AbstractTableModel;

public class BasicGUI extends javax.swing.JFrame {
  //BasicGUI subclass is always open unless logging in
  //Refresh button necessary to update information shown
  public BasicUser LoggedInUser = null;
  HashMap<String, ArrayList<Announcement>> groupAnnouncement = null;
  //ArrayList<ArrayList<Announcement>> groupAnnouncements = new ArrayList<>();
  
  public BasicGUI(BasicUser user){
    this.LoggedInUser = user;
    this.groupAnnouncement = new HashMap<>();
    this.initComponents();
    this.initAnnouncementTables();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    exitButton = new javax.swing.JButton();
    announcementsLabel = new javax.swing.JLabel();
    refreshButton = new javax.swing.JButton();
    communityTabs = new javax.swing.JTabbedPane();
    welcomeLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    exitButton.setText("Exit");
    exitButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        exitButtonActionPerformed(evt);
      }
    });

    announcementsLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    announcementsLabel.setText("Announcements");

    refreshButton.setText("Refresh");
    refreshButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        refreshButtonActionPerformed(evt);
      }
    });

    welcomeLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    welcomeLabel.setText("Welcome, user!");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap(607, Short.MAX_VALUE)
            .addComponent(exitButton))
          .addGroup(layout.createSequentialGroup()
            .addGap(285, 285, 285)
            .addComponent(announcementsLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(refreshButton))
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(communityTabs)))
        .addContainerGap())
      .addGroup(layout.createSequentialGroup()
        .addGap(250, 250, 250)
        .addComponent(welcomeLabel)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(welcomeLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(announcementsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(communityTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(exitButton)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
    try {
      new LoginGUI(new javax.swing.JFrame(), true).setVisible(true);
    } catch(Exception ex) {
      Logger.getLogger(HighPermUserGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
    this.dispose();
  }//GEN-LAST:event_exitButtonActionPerformed

  private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
    this.updateAnnouncementTables();
  }//GEN-LAST:event_refreshButtonActionPerformed

  public void initAnnouncementTables(){
    ArrayList<Announcement> announcementData = Database.getRecentAnnouncements(this.LoggedInUser);
    
    //Ensure first tab is 'public'
    {
      ArrayList<Announcement> pubList = Database.getPublicAnnouncements();
      this.groupAnnouncement.put("public", pubList);
      this.communityTabs.addTab("public", new AnnouncementTable(pubList));
    }

    Iterator iter = this.LoggedInUser.legalGroups.iterator();
    while(iter.hasNext()){
      Group curr = (Group)iter.next();
      String nam = curr.name;
      if(nam.equals("public")){
        continue;
      }
      ArrayList<Announcement> temp = new ArrayList<>();

      for(int j = 0; j < announcementData.size(); ++j){
        if(nam.equals(announcementData.get(j).group.name)){
          temp.add(announcementData.get(j));
        }
      }

      this.groupAnnouncement.put(nam, temp);
      this.communityTabs.addTab(nam, new AnnouncementTable(temp));
    }
  }
  
  public void updateAnnouncementTables(){
    //this.communityTabs;
    //this.groupAnnouncement;
    
    Iterator iter = this.groupAnnouncement.keySet().iterator();
    while(iter.hasNext()){
      String key = (String)iter.next();
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel announcementsLabel;
  private javax.swing.JTabbedPane communityTabs;
  private javax.swing.JButton exitButton;
  private javax.swing.JButton refreshButton;
  private javax.swing.JLabel welcomeLabel;
  // End of variables declaration//GEN-END:variables
}
