package communityhub.gui;

import communityhub.Announcement;
import communityhub.DB.Database;
import communityhub.users.BasicUser;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.AbstractTableModel;

public class BasicGUI extends javax.swing.JFrame {
  //BasicGUI subclass is always open unless logging in
  //Refresh button necessary to update information shown
  public BasicUser LoggedInUser = null;
  ArrayList<Announcement> announcementData = new ArrayList<Announcement>();
  
  public BasicGUI(BasicUser user){
    this.LoggedInUser = user;
    this.initComponents();
    this.updateAnnouncementTable();

    announcementTable.getColumnModel().getColumn(0).setHeaderValue("Author");
    announcementTable.getColumnModel().getColumn(1).setHeaderValue("Title");
    announcementTable.getColumnModel().getColumn(2).setHeaderValue("Body");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    announcementTable = new javax.swing.JTable();
    exitButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosed(java.awt.event.WindowEvent evt) {
        formWindowClosed(evt);
      }
    });

    announcementTable.setModel(new AbstractTableModel()
      {
        @Override
        public int getRowCount()
        {
          return announcementData.size();
        }

        @Override
        public int getColumnCount()
        {
          return 3;
        }

        @Override
        public String getValueAt(int i, int j)
        {
          String temp = null;
          switch (j)
          {
            case 0:
            temp = announcementData.get(i).author;
            break;
            case 1:
            temp = announcementData.get(i).title;
            break;
            case 2:
            temp = announcementData.get(i).body;
            break;
          }
          return temp;
        }

        public void setValueAt(String val, int i, int j)
        {
          switch (j)
          {
            case 1:
            announcementData.get(i).author = val;
            break;
            case 2:
            announcementData.get(i).title = val;
            break;
            case 3:
            announcementData.get(i).body = val;
            break;
          }
        }
      });
      jScrollPane1.setViewportView(announcementTable);

      exitButton.setText("Exit");
      exitButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          exitButtonActionPerformed(evt);
        }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addContainerGap()
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
              .addGap(0, 597, Short.MAX_VALUE)
              .addComponent(exitButton))
            .addComponent(jScrollPane1))
          .addContainerGap())
      );
      layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addContainerGap(157, Short.MAX_VALUE)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(18, 18, 18)
          .addComponent(exitButton)
          .addContainerGap())
      );

      pack();
    }// </editor-fold>//GEN-END:initComponents

  private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
    try {
      new LoginGUI(new javax.swing.JFrame(), true).setVisible(true);
    } catch(Exception ex) {
      Logger.getLogger(HighPermUserGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
    this.dispose();
  }//GEN-LAST:event_exitButtonActionPerformed

  private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
  }//GEN-LAST:event_formWindowClosed

  public void updateAnnouncementTable(){
    this.announcementData = Database.getRecentAnnouncements();

    for(int i = 0; i < announcementData.size(); i++){
      this.announcementTable.setValueAt(announcementData.get(i).author, i, 0);
      this.announcementTable.setValueAt(announcementData.get(i).title, i, 1);
      this.announcementTable.setValueAt(announcementData.get(i).body, i, 2);
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  protected javax.swing.JTable announcementTable;
  private javax.swing.JButton exitButton;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables
}
